name: Teste

on:
  push:
    branches:
      - main  # Executa o workflow quando há push na branch 'main'

jobs:
  deploy:
    runs-on: ubuntu-latest  # Máquina virtual Ubuntu

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3  # Obtém o código do repositório

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"  # Defina a versão do Python desejada

      - name: Instalar dependências
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: Finalizar deploy
        run: echo "Todas as dependências foram instaladas com sucesso!"
